### ISSUE TITLE
English documentation

### ISSUE THREAD

**Issue by ghost** [SymfonyId/GammuBundle#1]
It would be nice if this bundle is fully available with english documentation.
Is this bundle still maintained?

**Comment by ad3n** [comment]
Hi @JHGitty : This bundle is not longer maintenance because i have no time for code maintenance. But thanks for your response. You can fork and then modify this bundle.

This bundle is so simple and i think you can use it without any documentation.

**Comment by ghost** [comment]
Thanks! :+1:
